[package]
name = "navmesh"
version = "0.2.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
petgraph = "0.6"

[dependencies.bevy]
version = "0.8.0"
features = ["render", "bevy_winit", "bevy_asset", "bevy_scene"]
default-features = false

[dev-dependencies]
rand = "0.8"

[features]
default = []
linuxci = ["bevy/x11"]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1
